CDM-34: Create Navbar component
cdm-mps/creativestudio pull request #20
Opened 2024-01-09 18:07 UTC by danielaprado

### Description

- Create Navbar component
- Desktop & Mobile responsive

### Attachments
- **Desktop**
![image](https://github.com/cdm-mps/creativestudio/assets/93549975/cc72f825-9594-45c5-85c7-1b391b3f4309)
- **Mobile**
![image](https://github.com/cdm-mps/creativestudio/assets/93549975/5bb57793-b825-45ad-a408-fae33eee3919)
![image](https://github.com/cdm-mps/creativestudio/assets/93549975/c9c6a821-57ea-4111-b8ee-8856f6bd64c8)

### Reviewers

- [ ] @catarinapm 
- [ ] @mariasbl

2024-01-09 20:42 UTC, catarinapm reviewed
I would suggest that in the mobile version the on press would make the backgound blue and the text would be white. Instead of underline as the Web version. We can discuss this!

2024-01-09 20:42 UTC, catarinapm commented on fe/app/components/Navbar/MenuOptions/MenuOptions.tsx
Why don't you create a function with that repeated <Link> and pass the variables such as category and label?
Also, the onClick is suppose to be the same for every <Link>?

2024-01-09 20:47 UTC, catarinapm requested changes
Also the navbar should be floating, right?

2024-01-10 16:32 UTC, danielaprado commented on fe/app/components/Navbar/MenuOptions/MenuOptions.tsx
U right, doing it!
Yes they all go to to different routes (href) but when clicking on the option we want to close the menu

2024-01-10 18:02 UTC, catarinapm approved these changes
Thank youu!

2024-01-10 18:04 UTC, mariasbl approved these changes

2024-01-10 18:05 UTC, merged