CDM-16: New Sponsors component
cdm-mps/creativestudio pull request #42
Opened 2024-01-14 22:28 UTC by catarinapm

[WEB]
![image](https://github.com/cdm-mps/creativestudio/assets/129984310/d6befcac-93b5-44ec-b90a-c866dc8bb197)

[MOBILE]
![image](https://github.com/cdm-mps/creativestudio/assets/129984310/78a0aeef-8371-444f-ad64-28cc4cc61df5)

2024-01-14 22:46 UTC, danielaprado requested changes

2024-01-14 22:46 UTC, danielaprado commented on fe/app/components/Sponsors/Sponsors.tsx
> +        {sponsors.map((e: Sponsor) => (
Can you update `e` to `sponsor`?

2024-01-14 22:46 UTC, danielaprado commented on fe/app/components/Sponsors/Sponsors.models.tsx
> +  [x: string]: any;
Is this ever used? 🤔

2024-01-14 22:48 UTC, catarinapm commented on fe/app/components/Sponsors/Sponsors.models.tsx
> +  [x: string]: any;
whaaaa wtfuge is this?

2024-01-14 22:48 UTC, catarinapm commented on fe/app/components/Sponsors/Sponsors.tsx
> +        {sponsors.map((e: Sponsor) => (
yes sir 👌

2024-01-14 22:56 UTC, danielaprado approved these changes
LGTM 🚀

2024-01-15 12:30 UTC, mariasbl approved these changes

2024-01-15 12:37 UTC, merged